#! /bin/sh


killall -w sxhkd picom polybar &
sleep 0.1

# map caps lock to escape
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
#hide mouse while typing
unclutter idle 2 &

picom &
# start libinput-gestures
libinput-gestures-setup start

feh --bg-fill --no-fehbg --randomize ~/Images/Wallpapers
sxhkd & 

external_monitor=$(xrandr --query | grep 'HDMI-0')
if [[ $external_monitor = *connected* ]]; 
then
    xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of eDP-1-1 
    bspc wm --reorder-monitors HDMI-0 eDP-1-1
    bspc monitor HDMI-0 -d a b c d e 
    bspc monitor eDP-1-1 -d f g h i j 
    
    polybar main -c $HOME/.config/polybar/configMonitor.ini 2> /dev/null &
    sleep 0.1
    polybar secondary -c $HOME/.config/polybar/configMonitor.ini 2> /dev/null &
else
    bspc monitor -d a b c d e 
    echo xwaka
    polybar main -c $HOME/.config/polybar/config.ini 2> /dev/null &
fi

bspc config border_width          0
bspc config window_gap            25
#bspc config top_padding           25
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false 
bspc config focus_follows_pointer false

bspc rule -a feh state=floating
bspc rule -a firefox desktop='^2' follow=on focus=on 
bspc rule -a Thunar desktop='^5' follow=on focus=on 
bspc rule -a Chromium desktop='^2' follow=on 
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a "QML Timer" state=pseudo_tiled
bspc rule -a mpv desktop='^4' follow=on state=pseudo_tiled
bspc rule -a vlc desktop='^4' follow=on state=pseudo_tiled

#$HOME/.config/polybar/launch.sh
